<button id="scroll"></button>
	<nav>
	<ul>
		<li id="index"><a href="index.php">Home</a></li>
		<li><a href="jobs.php">Job Description</a></li>
		<li><a href="apply.php">Job Application</a></li>
		<li><a href="about.php">About Me</a></li>
		<li><a href="enhancements.php">Enhancements</a></li> 
		<li><a href="enhancements2.php">Enhancements Two</a></li> 
		<li><a href="phpenhancements.php">PHP Enhancements</a></li> 	
	</ul>
	</nav>
	